--USAMOS EL USUARIO MAESTRO, EL WAREHOUSE QUE TENEMOS Y LA BD REQUERIDA
USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;

--CREAMOS LA BASE DE DATOS PARA TRABAJAR
CREATE DATABASE RETAIL_TRANSACTIONS;
USE DATABASE RETAIL_TRANSACTIONS;

--CREAMOS LOS SCHEMAS DE LA ARQUITECTURA MEDALLON
CREATE OR REPLACE SCHEMA RETAIL_TRANSACTIONS.BRONZE;
CREATE OR REPLACE SCHEMA RETAIL_TRANSACTIONS.SILVER;
CREATE OR REPLACE SCHEMA RETAIL_TRANSACTIONS.GOLD;

--CREANDO EL FILE FORMAT PARA QUE SNOWFLAKE LEA BIEN EL ARCHIVO CSV
CREATE OR REPLACE FILE FORMAT RETAIL_TRANSACTIONS.BRONZE.CSV_GENERIC_FORMAT
    TYPE = 'CSV'
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY ='"'
    NULL_IF = ('NULL', 'null', '')
    EMPTY_FIELD_AS_NULL = TRUE;

--CREANDO EL INTERNAL STAGE DONDE ATERRIZA LA RAWDATA
CREATE OR REPLACE STAGE RETAIL_TRANSACTIONS.BRONZE.STG_RAW_DATA
    DIRECTORY = (ENABLE = TRUE)
    FILE_FORMAT = RETAIL_TRANSACTIONS.BRONZE.CSV_GENERIC_FORMAT;

-- CAPA BRONZE

--CREANDO LA TABALA DONDE SE COPIARAN LOS DATOS
CREATE OR REPLACE TABLE RETAIL_TRANSACTIONS.BRONZE.RAW_DATA(
    Customer_ID varchar,
    Product_ID varchar,
    Quantity varchar,
    Price varchar,
    Transaction_Date varchar,
    Payment_Method varchar,
    Store_Location varchar,
    Product_Category varchar,
    Discount_Applied varchar,
    Total_Amount varchar
);

--COPIANDO DEL ARCHIVO CSV A LA TABLA QUE ACABO DE CREAR
COPY INTO RETAIL_TRANSACTIONS.BRONZE.RAW_DATA
FROM @RETAIL_TRANSACTIONS.BRONZE.STG_RAW_DATA
FILES = ('Retail_Transaction_Dataset.csv')
FILE_FORMAT = (FORMAT_NAME = 'RETAIL_TRANSACTIONS.BRONZE.CSV_GENERIC_FORMAT')
ON_ERROR = CONTINUE;

-- VALIDANDO LA CARGA DE DATOS EN LA ARQUITECTURA MEDALLON
SELECT * FROM RETAIL_TRANSACTIONS.BRONZE.RAW_DATA LIMIT 10;

-- CAPA SILVER

-- HACIENDO LA TRANSFORMACION DE LAS COLUMNAS
CREATE OR REPLACE TABLE RETAIL_TRANSACTIONS.SILVER.CLEANED_RETAIL_DATA AS
SELECT
    TRY_TO_NUMBER(TRIM(CUSTOMER_ID)) AS CUSTOMER_ID,
    UPPER(TRIM(PRODUCT_ID)) AS PRODUCT_ID,
    TRY_TO_NUMBER(TRIM(QUANTITY)) AS QUANTITY,
    TRY_TO_DOUBLE(PRICE) AS PRICE,
    TO_TIMESTAMP(TRANSACTION_DATE,'MM/DD/YYYY HH24:MI') AS TRANSACTION_TIMESTAMP,
    COALESCE(UPPER(TRIM(PAYMENT_METHOD)), 'UNKNOWN') AS PAYMENT_METHOD,
    TRIM(STORE_LOCATION) AS FULL_ADDRESS,
    COALESCE(
        REGEXP_SUBSTR(STORE_LOCATION, ' ([A-Z]{2}) [0-9]{5}$', 1, 1, 'e'), 'UNKNOWN'
    ) AS STORE_STATE,
    UPPER(TRIM(PRODUCT_CATEGORY)) AS PRODUCT_CATEGORY,
    COALESCE(TRY_TO_DOUBLE(DISCOUNT_APPLIED), 0) AS DISCOUNT_PERCENT,
    TRY_TO_DOUBLE(TOTAL_AMOUNT) AS TOTAL_AMOUNT,
    CURRENT_TIMESTAMP() AS LOAD_TIMESTAMP
FROM RETAIL_TRANSACTIONS.BRONZE.RAW_DATA
WHERE
    CUSTOMER_ID IS NOT NULL
    AND TRANSACTION_TIMESTAMP IS NOT NULL
    AND TOTAL_AMOUNT IS NOT NULL;

-- VALIDANDO QUE SE HAYAN CASTEADO BIEN LAS COLUMNAS
DESCRIBE TABLE RETAIL_TRANSACTIONS.SILVER.CLEANED_RETAIL_DATA;

-- CAPA GOLD

-- INSIGHT 1: Análisis de Rentabilidad por Categoría
-- Identificar qué categorías generan más dinero a pesar de los descuentos y cuáles dependen demasiado de las ofertas para vender

CREATE OR REPLACE VIEW RETAIL_TRANSACTIONS.GOLD.VW_RENTABILIDAD_POR_CATEGORIA AS
SELECT
    PRODUCT_CATEGORY,
    SUM(TOTAL_AMOUNT) AS TOTAL_REVENUE,
    AVG(DISCOUNT_PERCENT) AS AVG_DISCOUNT_PERCENT
FROM RETAIL_TRANSACTIONS.SILVER.CLEANED_RETAIL_DATA
GROUP BY PRODUCT_CATEGORY
ORDER BY PRODUCT_CATEGORY DESC;

SELECT * FROM RETAIL_TRANSACTIONS.GOLD.VW_RENTABILIDAD_POR_CATEGORIA LIMIT 10;

-- INSIGHT 2: Rendimiento Geográfico
-- Detectar zonas geográficas con bajo rendimiento para campañas de marketing focalizadas. Ventas totales y cantidad de transacciones agrupadas por el Estado

CREATE OR REPLACE VIEW RETAIL_TRANSACTIONS.GOLD.VW_RENDIMIENTO_GEOGRAFICO AS
SELECT
    STORE_STATE,
    SUM(TOTAL_AMOUNT) AS TOTAL_REVENUE,
    COUNT(*) AS TRANSACTIONS_QTY
FROM RETAIL_TRANSACTIONS.SILVER.CLEANED_RETAIL_DATA
GROUP BY STORE_STATE
ORDER BY TOTAL_REVENUE ASC;

SELECT * FROM RETAIL_TRANSACTIONS.GOLD.VW_RENDIMIENTO_GEOGRAFICO LIMIT 10;

-- INSIGHT 3: Tendencia Temporal y Estacionalidad
-- Ventas diarias y mensuales (usando DATE_TRUNC). Identificar picos de venta (fines de semana vs días de semana) y crecimiento mes a mes (MoM).

CREATE OR REPLACE VIEW RETAIL_TRANSACTIONS.GOLD.VW_TENDENCIA_VS_ESTACIONALIDAD AS 
SELECT
    DATE_TRUNC('DAY', TRANSACTION_TIMESTAMP) AS TRANSACTION_DAY,
    DATE_TRUNC('MONTH', TRANSACTION_TIMESTAMP) AS TRANSACTION_MONTH,
    SUM(TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM RETAIL_TRANSACTIONS.SILVER.CLEANED_RETAIL_DATA
GROUP BY 1, 2;

SELECT * FROM RETAIL_TRANSACTIONS.GOLD.VW_TENDENCIA_VS_ESTACIONALIDAD LIMIT 10;

-- INSIGHT 4: Análisis de Métodos de Pago
-- Participación de cada método de pago en el volumen total. Ver si ciertos métodos de pago están asociados a tickets más altos.

CREATE OR REPLACE VIEW RETAIL_TRANSACTIONS.GOLD.VW_METODO_PAGO_ANALISIS AS
SELECT
    PAYMENT_METHOD,
    SUM(TOTAL_AMOUNT) AS TOTAL_REVENUE,
    AVG(TOTAL_AMOUNT) AS AVG_TICKET_VALUE
FROM RETAIL_TRANSACTIONS.SILVER.CLEANED_RETAIL_DATA
GROUP BY PAYMENT_METHOD
ORDER BY TOTAL_REVENUE DESC;

SELECT * FROM RETAIL_TRANSACTIONS.GOLD.VW_METODO_PAGO_ANALISIS LIMIT 10;

-- INSIGHT 5: Efectividad del Descuento
-- Correlación entre el porcentaje de descuento y el volumen de unidades vendidas. Determinar si aumentar el descuento realmente impulsa el volumen de ventas o solo reduce el margen.

CREATE OR REPLACE VIEW RETAIL_TRANSACTIONS.GOLD.VW_EFECTIVIDAD_DESCUENTO AS
SELECT
    CASE
        WHEN DISCOUNT_PERCENT < 5 THEN '0 - 5%'
        WHEN DISCOUNT_PERCENT < 10 THEN '5 - 10%'
        WHEN DISCOUNT_PERCENT < 15 THEN '10 - 15%'
        ELSE '15 - 20%'
    END AS DISCOUNT_RANGE,
    SUM(QUANTITY) AS TOTAL_UNITS_SOLD
FROM RETAIL_TRANSACTIONS.SILVER.CLEANED_RETAIL_DATA
GROUP BY 1
ORDER BY DISCOUNT_RANGE ASC;

SELECT * FROM RETAIL_TRANSACTIONS.GOLD.VW_EFECTIVIDAD_DESCUENTO LIMIT 10;


-- INSIGHT 6: Ranking de Productos "Best-Sellers"
-- Top 10 ProductID por volumen de ventas y por ingresos.

CREATE OR REPLACE VIEW RETAIL_TRANSACTIONS.GOLD.VW_RANKING_PRODUCTS AS
SELECT
    PRODUCT_ID,
    SUM(QUANTITY) AS TOTAL_QTY_SOLD,
    SUM(TOTAL_AMOUNT) AS TOTAL_REVENUE,
FROM RETAIL_TRANSACTIONS.SILVER.CLEANED_RETAIL_DATA
GROUP BY PRODUCT_ID
ORDER BY TOTAL_REVENUE
DESC LIMIT 10;

SELECT * FROM RETAIL_TRANSACTIONS.GOLD.VW_RANKING_PRODUCTS;

-- INSIGHT 7: KPI de Canasta Promedio (Average Basket Size)
-- Calcular el promedio de la columna Quantity por transacción. Medir la eficiencia de las ventas cruzadas (cross-selling).

CREATE OR REPLACE VIEW RETAIL_TRANSACTIONS.GOLD.VW_KPI_CANASTA_PROMEDIO AS
SELECT
    PRODUCT_CATEGORY,
    AVG(QUANTITY) AS AVG_BASKET_SIZE
FROM RETAIL_TRANSACTIONS.SILVER.CLEANED_RETAIL_DATA
GROUP BY PRODUCT_CATEGORY;

SELECT * FROM RETAIL_TRANSACTIONS.GOLD.VW_KPI_CANASTA_PROMEDIO;